-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgLv4m8pB3Bj4IxEQ8
CGfgWeaeyBPnKjwbygDycGhC7HygCgYIKoZIzj0DAQehRANCAAQp9TrdisYjmDRe
+CSedNYzkXO8JbayqsW+lpgjutTgKmVjuQqsMWCnfxRnACExWWwaNNMWYNOX3Z2B
/MCdmdn7
-----END PRIVATE KEY-----